# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furniture',
            old_name='price',
            new_name='newPrice',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='type',
        ),
        migrations.AddField(
            model_name='furniture',
            name='oldPrice',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furniture',
            name='saleType',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
