# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='unconfirmed', max_length=50),
            preserve_default=False,
        ),
    ]
