# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decorator',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Order')),
            ],
            bases=('orders.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='bonus',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TacamuriDecorator',
            fields=[
                ('decorator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Decorator')),
            ],
            bases=('orders.decorator',),
        ),
        migrations.CreateModel(
            name='TigaieDecorator',
            fields=[
                ('decorator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Decorator')),
            ],
            bases=('orders.decorator',),
        ),
    ]
